"""empty message

Revision ID: 281436639521
Revises: c66699ad6802
Create Date: 2023-01-22 16:51:50.926287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281436639521'
down_revision = 'c66699ad6802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
