"""empty message

Revision ID: 4d840c7ed798
Revises: 7cd1ac61d99a
Create Date: 2023-01-25 10:47:04.008419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d840c7ed798'
down_revision = '7cd1ac61d99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')

    # ### end Alembic commands ###
